//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VersInformer.Form.Client.VersInformerServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/VersInformer.Service.Entity")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/VersInformer.Service.Entity")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VersInformerServiceRef.IVersInformer", CallbackContract=typeof(VersInformer.Form.Client.VersInformerServiceRef.IVersInformerCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IVersInformer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVersInformer/Connect", ReplyAction="http://tempuri.org/IVersInformer/ConnectResponse")]
        bool Connect(VersInformer.Form.Client.VersInformerServiceRef.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVersInformer/Connect", ReplyAction="http://tempuri.org/IVersInformer/ConnectResponse")]
        System.Threading.Tasks.Task<bool> ConnectAsync(VersInformer.Form.Client.VersInformerServiceRef.Client client);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsTerminating=true, Action="http://tempuri.org/IVersInformer/Disconnect")]
        void Disconnect(VersInformer.Form.Client.VersInformerServiceRef.Client client);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsTerminating=true, Action="http://tempuri.org/IVersInformer/Disconnect")]
        System.Threading.Tasks.Task DisconnectAsync(VersInformer.Form.Client.VersInformerServiceRef.Client client);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/SendMessage")]
        void SendMessage(VersInformer.Form.Client.VersInformerServiceRef.Message msg);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/SendMessage")]
        System.Threading.Tasks.Task SendMessageAsync(VersInformer.Form.Client.VersInformerServiceRef.Message msg);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/VersiyonAliniyor")]
        void VersiyonAliniyor();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/VersiyonAliniyor")]
        System.Threading.Tasks.Task VersiyonAliniyorAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/VersiyonAlinacak")]
        void VersiyonAlinacak();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/VersiyonAlinacak")]
        System.Threading.Tasks.Task VersiyonAlinacakAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/VersiyonTesteHazir")]
        void VersiyonTesteHazir();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/VersiyonTesteHazir")]
        System.Threading.Tasks.Task VersiyonTesteHazirAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/VersiyonAlindi")]
        void VersiyonAlindi();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/VersiyonAlindi")]
        System.Threading.Tasks.Task VersiyonAlindiAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/YemekListesi")]
        void YemekListesi();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/YemekListesi")]
        System.Threading.Tasks.Task YemekListesiAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVersInformerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/RefreshClients")]
        void RefreshClients(VersInformer.Form.Client.VersInformerServiceRef.Client[] clients);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/OnMessage")]
        void OnMessage(VersInformer.Form.Client.VersInformerServiceRef.Message msg);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/UserJoin")]
        void UserJoin(VersInformer.Form.Client.VersInformerServiceRef.Client client);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/UserLeave")]
        void UserLeave(VersInformer.Form.Client.VersInformerServiceRef.Client client);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/OnVersiyonAlinacak")]
        void OnVersiyonAlinacak();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/OnVersiyonAliniyor")]
        void OnVersiyonAliniyor();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/OnVersiyonTesteHazir")]
        void OnVersiyonTesteHazir();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/OnVersiyonAlindi")]
        void OnVersiyonAlindi();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVersInformer/OnAciktikArtik")]
        void OnAciktikArtik();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVersInformerChannel : VersInformer.Form.Client.VersInformerServiceRef.IVersInformer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VersInformerClient : System.ServiceModel.DuplexClientBase<VersInformer.Form.Client.VersInformerServiceRef.IVersInformer>, VersInformer.Form.Client.VersInformerServiceRef.IVersInformer {
        
        public VersInformerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public VersInformerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public VersInformerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public VersInformerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public VersInformerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool Connect(VersInformer.Form.Client.VersInformerServiceRef.Client client) {
            return base.Channel.Connect(client);
        }
        
        public System.Threading.Tasks.Task<bool> ConnectAsync(VersInformer.Form.Client.VersInformerServiceRef.Client client) {
            return base.Channel.ConnectAsync(client);
        }
        
        public void Disconnect(VersInformer.Form.Client.VersInformerServiceRef.Client client) {
            base.Channel.Disconnect(client);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(VersInformer.Form.Client.VersInformerServiceRef.Client client) {
            return base.Channel.DisconnectAsync(client);
        }
        
        public void SendMessage(VersInformer.Form.Client.VersInformerServiceRef.Message msg) {
            base.Channel.SendMessage(msg);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(VersInformer.Form.Client.VersInformerServiceRef.Message msg) {
            return base.Channel.SendMessageAsync(msg);
        }
        
        public void VersiyonAliniyor() {
            base.Channel.VersiyonAliniyor();
        }
        
        public System.Threading.Tasks.Task VersiyonAliniyorAsync() {
            return base.Channel.VersiyonAliniyorAsync();
        }
        
        public void VersiyonAlinacak() {
            base.Channel.VersiyonAlinacak();
        }
        
        public System.Threading.Tasks.Task VersiyonAlinacakAsync() {
            return base.Channel.VersiyonAlinacakAsync();
        }
        
        public void VersiyonTesteHazir() {
            base.Channel.VersiyonTesteHazir();
        }
        
        public System.Threading.Tasks.Task VersiyonTesteHazirAsync() {
            return base.Channel.VersiyonTesteHazirAsync();
        }
        
        public void VersiyonAlindi() {
            base.Channel.VersiyonAlindi();
        }
        
        public System.Threading.Tasks.Task VersiyonAlindiAsync() {
            return base.Channel.VersiyonAlindiAsync();
        }
        
        public void YemekListesi() {
            base.Channel.YemekListesi();
        }
        
        public System.Threading.Tasks.Task YemekListesiAsync() {
            return base.Channel.YemekListesiAsync();
        }
    }
}
